
[ClassVersion("2.0.0.0")]
Class NetworkSettings
{
  [Write] string IpAddress;
  [Write] string Subnet;
  [Write] string DefaultGateway;
  [Write] string DnsServer;
};

[ClassVersion("2.0.0.0"), FriendlyName("VMNetworkAdapter")]
class DSC_VMNetworkAdapter : OMI_BaseResource
{
    [Key] String Id;
    [Required] String Name;
    [Required] String SwitchName;
    [Required] String VMName;
    [Write] String MacAddress;
    [Write] Boolean IgnoreNetworkSetting;
    [Write, EmbeddedInstance("NetworkSettings")] String NetworkSetting;
    [Write] String VlanId;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Read] Boolean DynamicMacAddress;
};
