[ClassVersion("1.0.0"), FriendlyName("VMScsiController")]
class DSC_VMScsiController : OMI_BaseResource
{
    [Key, Description("Specifies the name of the virtual machine whose SCSI controller is to be manipulated.")] String VMName;
    [Key, Description("Specifies the number of the SCSI controller to be set. If not specified, it defaults to 0."), ValueMap{"0","1","2","3"}, Values{"0","1","2","3"}] Uint32 ControllerNumber;
    [Write, Description("Specifies if the SCSI controller should exist or not. If not specified, it defaults to `Present`."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("If set to `$true` then shutdowns and restarts are allowed for the VM when needed for property changes. If not specified, it defaults to `$false`.")] Boolean RestartIfNeeded;
};
